name: Deploy to netlify and vercel!

on:
  push:
    branches:
      - master

jobs:
  deploy-netlify:
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit

  deploy-vercel:
    needs: deploy-netlify
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
